// <auto-generated />
using System;
using EmployeeManagement.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220216073939_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeManagement.Models.Departments", b =>
                {
                    b.Property<int>("departmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("departmentID"), 1L, 1);

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("departmentID");

                    b.ToTable("VarDepartments");

                    b.HasData(
                        new
                        {
                            departmentID = 1,
                            departmentName = "IT"
                        },
                        new
                        {
                            departmentID = 2,
                            departmentName = "HR"
                        });
                });

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("employeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeID"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("emailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("employeeID");

                    b.ToTable("VarEmployees");

                    b.HasData(
                        new
                        {
                            employeeID = 1,
                            DepartmentId = 1,
                            dateOfBirth = new DateTime(1982, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            emailID = "smartydarren@gmail.com",
                            firstName = "Darren",
                            gender = 0,
                            lastName = "Quadros",
                            photoPath = "images/Boy.jpg"
                        },
                        new
                        {
                            employeeID = 2,
                            DepartmentId = 2,
                            dateOfBirth = new DateTime(1985, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            emailID = "aislinn.quadros@gmail.com",
                            firstName = "Aislinn",
                            gender = 1,
                            lastName = "Quadros",
                            photoPath = "images/Girl.jpg"
                        },
                        new
                        {
                            employeeID = 3,
                            DepartmentId = 1,
                            dateOfBirth = new DateTime(1985, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            emailID = "denver.quadros@gmail.com",
                            firstName = "Denver",
                            gender = 0,
                            lastName = "Quadros",
                            photoPath = "images/Girl.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
